### ISSUE TITLE
Can't set column header and order options at the same time.

### ISSUE THREAD

**Issue by pmichna** [bogdan/datagrid#227] opened 2017-06-22 10:06 UTC
I can't have `header` and `order` column options at the same time.

Examples:

1. `column(:first_name, header: 'foo', order: 'users.first_name') { first_name }`
Only order works, header is `First_name`.

2. `column(:first_name, header: 'foo') { first_name }` 
Header is displayed correctly, i.e. `foo`.

**Comment by bogdan** [comment] 2017-06-22 12:23
I can not reproduce that. Are you sure that your app catches on class changes when you refresh the page?
Maybe there are special conditions inside your grid. Can you show me the whole grid source code?

Also `First_name` as a header is weird because the default header is `First name`.

**Comment by bogdan** [comment] 2017-07-05 08:54
No way to reproduce - closing

**Closed by bogdan** 2017-07-05 08:54 UTC
